### ISSUE TITLE
Support loading a "set of EXPRESS schemas"

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-express#4]
We want to allow a defined set (via YAML or XML) of EXPRESS schemas available for Metanorma to navigate.

This requires Expressir to have the following functionality:
* fully parse all the schemas and keep them around
* for speed reasons, Expressir should support exporting/importing a parsed cache that contains the schema set

This requires the Metanorma LutaML plugin to:
* support specifying of a "LutaML model cache" that wraps the Expressir cache (since we may also want UML caches, etc.)
* keep the LutaML parsed models available
* we will need to support different models of different families (EXPRESS, UML) in the same Metanorma document, so the different flavors of LutaML functionality need to play nice with each other

Thoughts @w00lf?

Once we have this confirmed we need to create the individual work tasks.

**Comment by w00lf** [comment]
> We want to allow a defined set (via YAML or XML) of EXPRESS schemas available for Metanorma to navigate.
> 
> This requires Expressir to have the following functionality:
> 
> * fully parse all the schemas and keep them around
> * for speed reasons, Expressir should support exporting/importing a parsed cache that contains the schema set
> 
> This requires the Metanorma LutaML plugin to:
> 
> * support specifying of a "LutaML model cache" that wraps the Expressir cache (since we may also want UML caches, etc.)
> * keep the LutaML parsed models available
> * we will need to support different models of different families (EXPRESS, UML) in the same Metanorma document, so the different flavors of LutaML functionality need to play nice with each other
> 
> Thoughts @w00lf?
> 
> Once we have this confirmed we need to create the individual work tasks.

So as far as I understand it needs to be a class level cache for Lutaml uml/expressir and also change all parsing methods to use cache in case we already have these uml/expressir entity available? How can we determine that we need to use cache in case of expressir repository? It will be identified by schema id? And in the case of lutaml how should we keep track of loaded models?

**Comment by ronaldtse** [comment]
In the case of EXPRESS, the caching mechanism should be implemented by Expressir. 

To break this down we want to have these modes:

1. User provides single schema file path to LutaML. LutaML asks Expressir to parse file and provide navigable object (parse tree/functionality).
2. User provides a set of schemas (via an index) to LutaML. LutaML asks Expressir to parse all those files and provide navigable object.
3. User provides a set of schemas (via an index) + a cached schema set file path to LutaML. LutaML asks Expressir to check/read/write the cache (if the cache is outdated, rebuild from the index, if not, read and use the cache) and provide navigable object.

**Comment by w00lf** [comment]
> In the case of EXPRESS, the caching mechanism should be implemented by Expressir.
> 
> To break this down we want to have these modes:
> 
> 1. User provides single schema file path to LutaML. LutaML asks Expressir to parse file and provide navigable object (parse tree/functionality).
> 2. User provides a set of schemas (via an index) to LutaML. LutaML asks Expressir to parse all those files and provide navigable object.
> 3. User provides a set of schemas (via an index) + a cached schema set file path to LutaML. LutaML asks Expressir to check/read/write the cache (if the cache is outdated, rebuild from the index, if not, read and use the cache) and provide navigable object.

First 2 cases pretty straightforward. Abotu the 3d one, how it will look in the documents itself? Something like: 
Initialize the cache:
```adoc
[lutaml,/path/to/index,context,cache=my_cache]
--
....
--
```

Used cached version:
[lutaml,/path/to/index,context,use_cache=my_cache]
--
....
--
```

**Comment by ronaldtse** [comment]
In the third case I was thinking of something like this:

```
== My title
:lutaml-express-index: first-express-set; /path/to/index; cache=/path/to/cache
:lutaml-express-index: second-express-set; /path/to/index; cache=/path/to/cache

[lutaml,first-express-set,context]
--
....
--

[lutaml,second-express-set,context]
--
....
--

```

**Comment by w00lf** [comment]
> In the third case I was thinking of something like this:
> 
> ```
> == My title
> :lutaml-express-index: first-express-set; /path/to/index; cache=/path/to/cache
> :lutaml-express-index: second-express-set; /path/to/index; cache=/path/to/cache
> 
> [lutaml,first-express-set,context]
> --
> ....
> --
> 
> [lutaml,second-express-set,context]
> --
> ....
> --
> ```

Ok, so it will be on document level, pretty simple. @ronaldtse  should I create tasks for expressir too or just lutaml related?

**Comment by ronaldtse** [comment]
Yes, document level. That's why we have the cache :wink: -- across documents, we can share the cache.

Can you please help create tasks for LutaML, the Metanorma plugin (and also Expressir if the corresponding task is not there)? Thanks!

**Comment by w00lf** [comment]
> Yes, document level. That's why we have the cache 😉 -- across documents, we can share the cache.
> 
> Can you please help create tasks for LutaML, the Metanorma plugin (and also Expressir if the corresponding task is not there)? Thanks!

Ok, got you, will do.

**Comment by ronaldtse** [comment]
@w00lf this is completed, right?

**Comment by w00lf** [comment]
@ronaldtse yes, this one was implemented in https://github.com/metanorma/metanorma-plugin-lutaml/pull/19 and https://github.com/metanorma/metanorma-plugin-lutaml/pull/25

**Comment by ronaldtse** [comment]
Thanks @w00lf !
