### ISSUE TITLE
Update to use latest Expressir

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/lutaml-express#6]
https://github.com/lutaml/expressir/pull/89 updates Expressir functionality with heavy clean up.

There are a few things we need to update, including:

* Module name of `Expressir::ExpressExp` is now `Expressir::Express`.
* expressir/express_exp is renamed to expressir/express
* from lutaml/expressir#77:

> Where class -> WhereRule
> Unique class -> UniqueRule

> Type / Entity / Rule class
> 
> * where -> where_rules
> * unique -> unique_rules

> Type class
> 
> * type -> underlying_type

> Types::Select / Types::Enumeration class
> 
> * extension_type -> based_on
> * extension_items -> items

(see full updates here: https://github.com/lutaml/expressir/pull/89#issue-617459881)

**Comment by ronaldtse** [comment]
According to @zakjan this will be Expressir 1.0.

**Comment by w00lf** [comment]
@ronaldtse updated all lutaml* gems to support expressir 1.0

**Comment by ronaldtse** [comment]
Can we close this now? Thanks.

**Comment by w00lf** [comment]
> Can we close this now? Thanks.

Yes, all gems updated
